### PR TITLE
Added new --with-cycles #373

### PR DESCRIPTION
**Pull request by Eve832**
**Overview**
Added the --with-cycles command and examples to dfx canister create and dfx deploy

### CODE REVIEW

**Comment by Eve832** [comment]
One issue for dfx deploy is that the Rel notes didn't state how you specify which backend canister to initialize with cycles. Unless there is only one for each project?

**Review by lsgunnlsgunn — CHANGES_REQUESTED** [review]
Two things:
- I think we have to increase the number of uncles in the examples (one trillion plus a fee in the minimum). Add some zeroes (I know t looks weird but 1T cycles = 1 USD). 
- "backend" is just a canister name example (could be "linkedup" or "calc") not a type of canister.

**Comment by lsgunnlsgunn** [comment]
dfx deploy backend means "only deploy canister-name backend" instead of all canisters in the project. Maybe something like "hello_assets" would be a better example

**Comment by Eve832** [comment]
You don't actually want me to mention a "fee" do you (zeros added, changing dfx deploy backend example)? @lsgunnlsgunn

**Review by lsgunnlsgunn — APPROVED** [review]

**Pull request merged**
